- name: Deploy config with CVP
  hosts: CVP
  connection: local
  gather_facts: no
  tasks:
    - name: Deploy Configurations to Devices
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        configlets_prefix: 'avd'
        execute_tasks: false
        container_root: 'DC1_HOSTS'